### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by jimfinnis** [atom/symbols-view#110]
[Enter steps to reproduce below:]

1. Install atom-ctags (which also threw an error)
2. Exit atom, go back in, atom-ctags rebuilds .tags correctly (in medium-size Java project)
3. Attempt to go to declaration of method in a Java file

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [symbols-view](https://github.com/atom/symbols-view) package, v0.99.0

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ATOM_SHELL_ASAR.js:118

Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:129:18)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/node_modules/ctags/lib/ctags.js:4:10)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/node_modules/ctags/lib/ctags.js:60:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/tag-reader.js:6:11)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/tag-reader.js:66:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/go-to-view.js:12:15)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/go-to-view.js:83:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.createGoToView (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/main.js:81:20)
  at atom-text-editor.editorSubscription.atom.commands.add.symbols-view:go-to-declaration (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/main.js:26:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -0:11.1.0 atomic-emacs:forward-char (atom-text-editor.editor.is-focused)
     -0:07.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:06.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.1.4
atomic-emacs, v0.7.1
language-supercollider, v0.2.0

# Dev
No dev packages
```

**Comment by dkarter** [comment]
I get this too.

**Comment by raccoonrat** [comment]
After reboot Atom, the issue OK.

**Comment by ssfrr** [comment]
I got this too, and it was fixed after restarting Atom.

Symbols-view was originally disabled by atom-ctags, and this issue happened after I uninstalled atom-ctags and re-enabled symbols-view.

**Comment by mico** [comment]
get same issue

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [symbols-view](https://github.com/atom/symbols-view) package, v0.100.0


### Stack Trace

Uncaught Error: Module did not self-register.

```
At ATOM_SHELL_ASAR.js:118

Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:129:18)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/node_modules/ctags/lib/ctags.js:4:10)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/node_modules/ctags/lib/ctags.js:60:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/tag-reader.js:6:11)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/tag-reader.js:66:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/go-to-view.js:12:15)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/go-to-view.js:83:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.createGoToView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/main.js:81:20)
  at atom-text-editor.editorSubscription.atom.commands.add.symbols-view:go-to-declaration (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/main.js:26:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -1:29 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
     -0:42.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:41.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:40.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:40.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:40.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:36.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:36.8.0 atom-ctags:rebuild (atom-text-editor.editor)
     -0:06.8.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -0:05.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:05.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.2.0
file-icons, v1.6.6
language-haml, v0.21.0
language-plantuml, v0.1.1
linter-haml, v1.0.0
linter-rubocop, v0.3.2
linter-ruby, v1.0.1

# Dev
No dev packages
```

**Comment by zenway-js** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [symbols-view](https://github.com/atom/symbols-view) package, v0.104.0


### Stack Trace

Uncaught Error: Module did not self-register.

```
At ATOM_SHELL_ASAR.js:137

Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:148:18)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\symbols-view\node_modules\ctags\lib\ctags.js:4:10)
  at Object.<anonymous> (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\symbols-view\node_modules\ctags\lib\ctags.js:60:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\symbols-view\lib\tag-reader.js:6:11)
  at Object.<anonymous> (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\symbols-view\lib\tag-reader.js:66:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\symbols-view\lib\go-to-view.js:12:15)
  at Object.<anonymous> (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\symbols-view\lib\go-to-view.js:83:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.createGoToView (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\symbols-view\lib\main.js:81:20)
  at atom-text-editor.editorSubscription.atom.commands.add.symbols-view:go-to-declaration (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\symbols-view\lib\main.js:26:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:145:19)
  at [object Object].jQuery.fn.trigger (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\src\space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\atom.asar\renderer\api\lib\remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:157:33)
  at HTMLDocument.handler (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\v.petrenko\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-commander, v0.3.5
atom-ctags, v4.3.0
autocomplete-ctags, v0.3.2
ctags-status, v1.3.3
git-diff-details, v0.20.0
git-log, v0.4.1
javascript-object-snippets, v0.3.0
javascript-snippets, v1.0.0
language-javascript-semantic, v0.2.1
linter, v1.8.1
linter-eslint, v3.1.0
minimap, v4.13.4
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
travis-ci-status, v0.18.0
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by CraryPrimitiveMan** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.1
**Thrown From**: [symbols-view](https://github.com/atom/symbols-view) package, v0.104.0


### Stack Trace

Uncaught Error: Module did not self-register.

```
At ATOM_SHELL_ASAR.js:137

Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:148:18)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/node_modules/ctags/lib/ctags.js:4:10)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/node_modules/ctags/lib/ctags.js:60:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/tag-reader.js:6:11)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/tag-reader.js:66:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/go-to-view.js:12:15)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/go-to-view.js:83:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.createGoToView (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/main.js:81:20)
  at atom-text-editor.editorSubscription.atom.commands.add.symbols-view:go-to-declaration (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/main.js:26:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:145:19)
  at [object Object].jQuery.fn.trigger (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:157:33)
  at HTMLDocument.handler (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-autocomplete-php",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-objective-c",
      "language-less",
      "language-csharp",
      "language-clojure",
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.3.0
editorconfig, v1.2.0
php-cs-fixer, v2.5.0

# Dev
No dev packages
```

**Comment by Skarlso** [comment]
Note => Restarting TWICE helped!

**Comment by bhack** [comment]
:+1:

**Comment by xs3c** [comment]
Me too! It must restart **TWICE** after installing atom-ctags

**Comment by hackbayonet** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: "Fedora release
**Thrown From**: [symbols-view](https://github.com/atom/symbols-view) package, v0.112.0


### Stack Trace

Uncaught Error: Module did not self-register.

```
At ATOM_SHELL_ASAR.js:159

Error: Module did not self-register.
    at Error (native)
    at process.module.(anonymous function) (ATOM_SHELL_ASAR.js:159:20)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:159:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:170:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/node_modules/ctags/lib/ctags.js:4:10)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/node_modules/ctags/lib/ctags.js:60:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/tag-reader.js:6:11)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/tag-reader.js:66:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/go-to-view.js:10:15)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/go-to-view.js:85:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.createGoToView (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/main.js:75:20)
    at atom-text-editor.editorSubscription.atom.commands.add.symbols-view:go-to-declaration (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/main.js:20:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1106:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:340:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
     -0:27.6.0 atom-ctags:toggle-file-symbols (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:27.5.0 blur (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:27.5.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:26.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:26.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:26.6.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:25.2.0 core:move-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:23.6.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:21.5.0 core:move-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:20.8.0 core:move-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:16.8.0 core:move-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:16.5.0 core:move-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:15.1.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
  7x -0:14 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:05.6.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:00.9.0 symbols-view:go-to-declaration (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.9
atom-ctags, v4.5.2
vim-mode, v0.65.1

# Dev
No dev packages
```
