### ISSUE TITLE
Uncaught TypeError: Cannot read property 'position' of undefined

### ISSUE THREAD

**Issue by KurtRMueller** [atom/symbols-view#115]
[Enter steps to reproduce below:]

1. open up a file
2. press `cmd-r` to bring up the menu for jumping to a specific method
3. close the file using your `cmd-w`
4. select a method from the menu.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [symbols-view](https://github.com/atom/symbols-view) package, v0.100.0

### Stack Trace

Uncaught TypeError: Cannot read property 'position' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/symbols-view.js:153

TypeError: Cannot read property 'position' of undefined
    at FileView.module.exports.SymbolsView.openTag (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/symbols-view.js:153:40)
    at FileView.module.exports.FileView.selectItemView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/file-view.js:77:21)
    at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:131:17)
    at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:14.2.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:13.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.mini.is-focused)
  5x -0:13.5.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:10.8.0 core:close (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:10.8.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:08.5.0 core:close (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:08.5.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:07.3.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:05.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:05.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:04.7.0 vim-mode:search (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:04.7.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:04.2.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.mini.is-focused)
  5x -0:04.1.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:01.7.0 core:close (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:01.7.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "useReactEditor": true,
    "disabledPackages": []
  }
}
```

### Installed Packages

```coffee
# User
ember-cli-helper, v0.7.2
ember-snippets, v1.4.0
html2haml, v0.10.0
language-cjsx, v0.3.0
language-ember-htmlbars, v0.3.0
language-emblem, v0.2.0
language-haml, v0.21.0
language-jade, v0.5.1
language-javascript-jsx, v0.3.7
language-puppet, v0.12.0
linter, v1.2.3
linter-clojure, v0.0.5
linter-ruby, v0.1.6
trailing-spaces, v0.3.2
vim-mode, v0.55.0

# Dev
No dev packages
```

**Comment by rokyed** [comment]
produced the bug with following: 
1.Open code file. 
2.Cmd+R(to show the method search)
3.Cmd+W(to close current tab)
4.Select any of the items in the method search and observe the bug.
