### ISSUE TITLE
Uncaught Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by cars000000** [atom/symbols-view#117]
[Enter steps to reproduce below:]

1.open any file
2.CTRL + R

**Atom Version**: 1.0.2
**System**: windows 8.1
**Thrown From**: [symbols-view](https://github.com/atom/symbols-view) package, v0.100.0

### Stack Trace

Uncaught Error: spawn UNKNOWN

```
At C:\Users\圣庭\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:260

Error: spawn UNKNOWN
    at exports._errnoException (util.js:734:11)
    at ChildProcess.spawn (child_process.js:1145:11)
    at Object.exports.spawn (child_process.js:977:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (C:\Users\圣庭\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:188:44)
    at new BufferedProcess (C:\Users\圣庭\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:50:14)
    at TagGenerator.module.exports.TagGenerator.generate (C:\Users\圣庭\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\symbols-view\lib\tag-generator.js:149:15)
    at FileView.module.exports.FileView.generateTags (C:\Users\圣庭\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\symbols-view\lib\file-view.js:144:62)
    at FileView.module.exports.FileView.populate (C:\Users\圣庭\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\symbols-view\lib\file-view.js:139:21)
    at FileView.module.exports.FileView.toggle (C:\Users\圣庭\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\symbols-view\lib\file-view.js:98:14)
    at atom-text-editor.editorSubscription.atom.commands.add.symbols-view:toggle-file-symbols (C:\Users\圣庭\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\symbols-view\lib\main.js:21:43)
```

### Commands

```
     -6:21.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  9x -6:15.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:11.7.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by adam-knights** [comment]
In addition to getting this error through the ctrl + r route described above I also see 'Spawn UNKNOWN' under settings -> Install -> Featured packages. 'Fetching featured packages failed' 'spawn UNKNOWN'

Windows 7, Atom 1.0.3
