### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by deterok** [atom/symbols-view#140]
[Enter steps to reproduce below:]
1. Open any file
2. Ctrl-R

**Atom Version**: 1.3.2
**System**: linux 4.3.2-gentoo-D4
**Thrown From**: [symbols-view](https://github.com/atom/symbols-view) package, v0.110.1
### Stack Trace

Uncaught Error: spawn EACCES

```
At /usr/share/atom/resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
    at /usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/tag-generator.js:117:18
    at TagGenerator.module.exports.TagGenerator.generate (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/tag-generator.js:115:14)
    at FileView.module.exports.FileView.generateTags (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/file-view.js:156:62)
    at FileView.module.exports.FileView.populate (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/file-view.js:151:21)
    at FileView.module.exports.FileView.toggle (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/file-view.js:98:14)
    at atom-text-editor.editorSubscription.atom.commands.add.symbols-view:toggle-file-symbols (/usr/share/atom/resources/app.asar/node_modules/symbols-view/lib/main.js:22:43)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -2:45.4.0 core:undo (atom-text-editor.editor.is-focused)
     -2:44.5.0 atom-html-preview:toggle (atom-text-editor.editor.is-focused)
     -2:41.6.0 encoding-selector:show (atom-text-editor.editor)
  2x -2:35.2.0 symbols-view:toggle-file-symbols (div.atom-html-preview.native-key-bindings)
     -2:28.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -2:25.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:23.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:23.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:19.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:15.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:14.8.0 core:undo (atom-text-editor.editor.is-focused)
  3x -2:13.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:11.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:49.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:48.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:03.7.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.19
atom-html-preview, v0.1.13

# Dev
No dev packages
```

**Comment by mtsmfm** [comment]
@deterok Could you confirm your permission for `symbols-view/vendor/ctags-linux` ?

In my environment, `$ sudo chmod +x /usr/share/atom/resources/app.asar.unpacked/node_modules/symbols-view/vendor/ctags-linux` solves this problem.
