### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by codra277** [atom/symbols-view#176]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: "Fedora release
**Thrown From**: [symbols-view](https://github.com/atom/symbols-view) package, v0.113.0

### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At /usr/share/atom/resources/app.asar/src/module-cache.js:280

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/codra/Downloads/symbols-view-master/lib/symbols-view.coffee:3:24)
    at Object.<anonymous> (/home/codra/Downloads/symbols-view-master/lib/symbols-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/codra/Downloads/symbols-view-master/lib/go-to-view.coffee:2:15)
    at Object.<anonymous> (/home/codra/Downloads/symbols-view-master/lib/go-to-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.createGoToView (/home/codra/Downloads/symbols-view-master/lib/main.coffee:52:18)
    at atom-text-editor.editorSubscription.atom.commands.add.symbols-view:go-to-declaration (/home/codra/Downloads/symbols-view-master/lib/main.coffee:10:45)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1106:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:327:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
     -0:00.9.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
symbols-view, v0.113.0

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
This package is bundled with Atom, so you should uninstall your manual install immediately. In addition, I'm assuming you installed this by cloning it, but forgot to execute `apm install` from the cloned repo root directory.
