### ISSUE TITLE
Uncaught Error: Cannot find module './.ctags'

### ISSUE THREAD

**Issue by LoneBoco** [atom/symbols-view#63]
I installed the latest version of atom from atom.io (0.165.0).  I opened it for the first time and tried pressing the CTRL+R hotkey.  The program locked up for a little while then spawned the following error:

```
Uncaught Error: Cannot find module './.ctags'
module.js:346

Error: Cannot find module './.ctags'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (\AppData\Local\atom\app-0.165.0\resources\app\src\module-cache.js:380:52)
  at Function.require.resolve (module.js:396:19)
  at TagGenerator.module.exports.TagGenerator.generate (\AppData\Local\atom\app-0.165.0\resources\app\node_modules\symbols-view\lib\tag-generator.js:89:34)
  at FileView.module.exports.FileView.generateTags (\AppData\Local\atom\app-0.165.0\resources\app\node_modules\symbols-view\lib\file-view.js:100:62)
  at FileView.module.exports.FileView.populate (\AppData\Local\atom\app-0.165.0\resources\app\node_modules\symbols-view\lib\file-view.js:95:21)
  at FileView.module.exports.FileView.toggle (\AppData\Local\atom\app-0.165.0\resources\app\node_modules\symbols-view\lib\file-view.js:72:14)
  at atom-text-editor.editorSubscription.atom.commands.add.symbols-view:toggle-file-symbols (\AppData\Local\atom\app-0.165.0\resources\app\node_modules\symbols-view\lib\main.js:21:43)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:243:29)
  at \AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (\AppData\Local\atom\app-0.165.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (\AppData\Local\atom\app-0.165.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (\AppData\Local\atom\app-0.165.0\resources\app\src\window-event-handler.js:167:20)
```

Interestingly enough, the button to create a new issue goes to http://git.io/BT-hJA , which is a 404 error.  I don't know who I should report that one to.

**Comment by mrkhanakia** [comment]
Hi
There can 2 reason that you are getting above error
1. ctags module is not installed
2. if ctags module installed correctly then NODE_PATH is not set which is causing error.
So i have Centos server and my shared node_modules are installed in that directory /usr/local/lib/node_modules

So i did SSH in my system as normal user (Not root user) and then did fire the following command
export NODE_PATH=/usr/local/lib/node_modules

**Comment by mrkhanakia** [comment]
Hi
There can 2 reason that you are getting above error
1. ctags module is not installed
2. if ctags module installed correctly then NODE_PATH is not set which is causing error.
So i have Centos server and my shared node_modules are installed in that directory /usr/local/lib/node_modules

So i did SSH in my system as normal user (Not root user) and then did fire the following command
export NODE_PATH=/usr/local/lib/node_modules

After that problem SOLVED
