### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by z3t0** [atom/symbols-view#68]
[Enter steps to reproduce below:]

1.Press Ctrl + R
2. Type a few keys
3. try and get rid of the dialog to search
4. hangs up for 5 seconds than the error shows up so I can report it

**Atom Version**: 0.174.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [symbols-view](https://github.com/atom/symbols-view) package, v0.79.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:391

TypeError: Cannot read property 'length' of undefined
  at TextBuffer.module.exports.TextBuffer.lineLengthForRow (c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:391:29)
  at TextBuffer.module.exports.TextBuffer.clipPosition (c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:943:53)
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\app\src\display-buffer.js:1009:27)
  at DisplayBuffer.module.exports.DisplayBuffer.scrollToBufferPosition (c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\app\src\display-buffer.js:661:47)
  at TextEditor.module.exports.TextEditor.scrollToBufferPosition (c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\app\src\text-editor.js:2670:33)
  at FileView.module.exports.SymbolsView.moveToPosition (c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\app\node_modules\symbols-view\lib\symbols-view.js:128:16)
  at FileView.module.exports.SymbolsView.openTag (c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\app\node_modules\symbols-view\lib\symbols-view.js:117:14)
  at FileView.module.exports.SymbolsView.confirmed (c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\app\node_modules\symbols-view\lib\symbols-view.js:92:21)
  at FileView.module.exports.SelectListView.confirmSelection (c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\app\node_modules\archive-view\node_modules\atom-space-pen-views\lib\select-list-view.js:335:21)
  at space-pen-li.<anonymous> (c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\app\node_modules\archive-view\node_modules\atom-space-pen-views\lib\select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\app\node_modules\archive-view\node_modules\atom-space-pen-views\node_modules\space-pen\vendor\jquery.js:4676:9)
  at HTMLOListElement.elemData.handle (c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\app\node_modules\archive-view\node_modules\atom-space-pen-views\node_modules\space-pen\vendor\jquery.js:4360:46)

```

### Commands

```
     -0:16.4 settings-view:open (atom-text-editor.editor.is-focused)
  2x -0:00.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by 0xdabbad00** [comment]
I have the same problem.  Before the error comes up, the search dialog comes up like it should for ctrl-r, but it only shows 3 lines, with the last one being:
```
ctags-win32: Warning: regcomp (,|^|\*/)[
Line NaN
```
I don't see anything like that line in my `tags` file.  I am running Atom on Windows, but I generated the `tags` file from a Linux guest vm that has a shared folder with my Windows host.

This failure occurs when I am looking at Go code.  It works when I am looking at Python code though.

**Comment by afontaine** [comment]
I have the same issue as @0xdabbad00, both with and without a `tags` file built for the project.

Running:
```
ctags --version
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul  9 2009, 17:05:35
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +win32, +regex, +internal-sort
```
