### ISSUE TITLE
Uncaught Error: Module version mismatch. Expected 17, got 41.

### ISSUE THREAD

**Issue by leanucci** [atom/symbols-view#72]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: [symbols-view](https://github.com/atom/symbols-view) package, v0.79.0

### Stack Trace

Uncaught Error: Module version mismatch. Expected 17, got 41.

```
At /Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422

Error: Module version mismatch. Expected 17, got 41.
  at Error (native)
  at Object.module.(anonymous function) [as .node] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/symbols-view/node_modules/ctags/lib/ctags.js:4:10)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/symbols-view/node_modules/ctags/lib/ctags.js:60:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/symbols-view/lib/tag-reader.js:6:11)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/symbols-view/lib/tag-reader.js:62:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/symbols-view/lib/go-to-view.js:12:15)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/symbols-view/lib/go-to-view.js:86:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.module.exports.createGoToView (/Applications/Atom.app/Contents/Resources/app/node_modules/symbols-view/lib/main.js:81:20)
  at atom-text-editor.editorSubscription.atom.commands.add.symbols-view:go-to-declaration (/Applications/Atom.app/Contents/Resources/app/node_modules/symbols-view/lib/main.js:26:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -1:29.1 snippets:next-tab-stop (atom-text-editor.editor)
     -1:29.1 snippets:expand (atom-text-editor.editor)
     -1:29.1 editor:indent (atom-text-editor.editor)
     -1:28.7 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -1:28.3 editor:select-to-end-of-word (atom-text-editor.editor)
     -1:27.9 editor:select-to-beginning-of-word (atom-text-editor.editor)
     -1:26.4 core:save (atom-text-editor.editor)
  4x -1:24.4 core:move-down (atom-text-editor.editor)
  2x -1:23.1 editor:newline (atom-text-editor.editor)
     -0:25.1 pane:show-previous-item (atom-text-editor.editor)
     -0:21.3 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:14.1 editor:move-to-first-character-of-line (atom-text-editor.editor)
     -0:13.9 editor:select-to-end-of-line (atom-text-editor.editor)
  4x -0:13.5 core:backspace (atom-text-editor.editor)
     -0:00.9 pane:show-previous-item (atom-text-editor.editor)
     -0:00.9 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "autobot-syntax-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v0.4.0
autobot-syntax-theme, v0.3.0
ember-cli-helper, v0.4.0
language-haml, v0.15.0
linter, v0.11.1
linter-rubocop, v0.2.1
project-manager, v1.15.5
travis-ci-status, v0.11.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment]
Can you try upgrading to 0.177 and see if this issue is resolved?

**Comment by leanucci** [comment]
I did right after submitting the ussue, and it seems to be fixed. Thanks for your reply!

**Comment by kevinsawicki** [comment]
Okay, closing this out, thanks for confirming.

**Comment by Intrepidd** [comment]
I have 0.177 and this issue is still present
