### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by kevinsawicki** [atom/symbols-view#89]
1. Open Atom
2. Open an existing file
3. Press `cmd-r`

**Atom Version**: 0.190.0-8c581c5
**System**: Mac OS X 10.10.2
**Thrown From**: [symbols-view](https://github.com/atom/symbols-view) package, v0.93.0

### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At child_process.js:1145

Error: spawn ENOTDIR
    at exports._errnoException (util.js:734:11)
    at ChildProcess.spawn (child_process.js:1145:11)
    at Object.exports.spawn (child_process.js:977:9)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:51:37)
    at TagGenerator.module.exports.TagGenerator.generate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/tag-generator.js:132:15)
    at FileView.module.exports.FileView.generateTags (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/file-view.js:100:62)
    at FileView.module.exports.FileView.populate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/file-view.js:95:21)
    at FileView.module.exports.FileView.toggle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/file-view.js:72:14)
    at atom-text-editor.editorSubscription.atom.commands.add.symbols-view:toggle-file-symbols (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/main.js:21:43)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:242:29)
```

### Commands

```
  2x -0:05.6 core:close (atom-text-editor.editor.is-focused)
     -0:05.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-one-dark-ui)
     -0:01.4 core:confirm (atom-text-editor.editor.mini)
     -0:00.8 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "feedback",
      "background-tips",
      "autosave"
    ],
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-atom-api, v0.7.0
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.8.0
autocomplete-snippets, v1.2.0
language-batch, v0.3.2
language-docker, v1.1.3
language-powershell, v2.0.0
language-typescript, v0.15.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
@zcbenz looks like this is no longer working on master when Atom is built with asar.

The specs still passed because they run from source, not the asar archive.
